[package]
name = "coreutils"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[[bin]]
name = "cat"
path = "src/bin/cat.rs"
test = false
bench = false

[[bin]]
name = "echo"
path = "src/bin/echo.rs"
test = false
bench = false

[[bin]]
name = "ls"
path = "src/bin/ls.rs"
test = false
bench = false

[[bin]]
name = "mkdir"
path = "src/bin/mkdir.rs"
test = false
bench = false

[[bin]]
name = "cp"
path = "src/bin/cp.rs"
test = false
bench = false

[[bin]]
name = "rm"
path = "src/bin/rm.rs"
test = false
bench = false

[[bin]]
name = "touch"
path = "src/bin/touch.rs"
test = false
bench = false

[[bin]]
name = "mv"
path = "src/bin/mv.rs"
test = false
bench = false

[dependencies]
