#!/bin/sh

set -eu

lb config noauto \
  --mode debian \
  --distribution trixie \
  --architecture amd64 \
  --binary-image iso-hybrid \
  --bootloaders "syslinux grub-efi" \
  --debian-installer none \
  --image-name millelith-os \
  "$@"